version: '3'
services:
    tenpo-backend:
        build: .
        container_name: 'tenpo-backend'
        ports:
            - "8080:8080"
        depends_on:
            - db
        networks:
            - backend
            - db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tenpo?serverTimezone=UTC
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=root
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    db:
        container_name: db
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: tenpo
        ports:
            - "5432:5432"
        volumes:
            - $HOME/Desktop/PostgreSql-Snippets/infile:/infile
            - pg_data:/var/lib/postgresql/data/
        networks:
            - db
networks:
    db:
    backend:
volumes:
    pg_data: